In [13]:
import pandas as pd

sales_data = py.read_csv(r"C:\Users\admin\PORKODI CLG\Data-Science-Learning\SalesData\data\sales_data.csv")
print(sales_data)

    OrderID        Date Customer     Product   Region  Quantity  Price  \
0      1001  2026-01-01     Asha      Laptop  Chennai         1  50000
1      1002  2026-01-02     Ravi       Mouse  Chennai         2    500
2      1003  2026-01-03    Kiran    Keyboard  Madurai         1   1500
3      1004  2026-01-04    Meena       Phone  Chennai         1  20000
4      1005  2026-01-05    Arjun      Laptop  Vellore         1  55000
5      1006  2026-01-06    Divya  Headphones    Salem         2   2000
6      1007  2026-01-07    Kavin     Monitor  Chennai         1  12000
7      1008  2026-01-08     Nila       Mouse   Trichy         3    500
8      1009  2026-01-09    Rahul    Keyboard    Erode         2   1500
9      1010  2026-01-10    Laksh       Phone  Chennai         1  22000
10     1011  2026-01-11  Porkodi      Laptop  Chennai         1  52000
11     1012  2026-01-12   Anitha     Monitor  Madurai         1  12500
12     1013  2026-01-13    Arjun       Mouse  Vellore         4    500
13     1014  2026-01-14    Meena  Headphones    Salem         1   2000
14     1015  2026-01-15     Ravi       Phone  Chennai         1  21000

    Total Sales
0         50000
1          1000
2          1500
3         20000
4         55000
5          4000
6         12000
7          1500
8          3000
9         22000
10        52000
11        12500
12         2000
13         2000
14        21000

In [14]:
#give first 5 data of sales
sales_data.head(5)

,OrderID,Date,Customer,Product,Region,Quantity,Price,Total Sales
0,1001,2026-01-01,Asha,Laptop,Chennai,1,50000,50000
1,1002,2026-01-02,Ravi,Mouse,Chennai,2,500,1000
2,1003,2026-01-03,Kiran,Keyboard,Madurai,1,1500,1500
3,1004,2026-01-04,Meena,Phone,Chennai,1,20000,20000
4,1005,2026-01-05,Arjun,Laptop,Vellore,1,55000,55000

In [15]:
#give last 5 data of sales
sales_data.tail(5)

,OrderID,Date,Customer,Product,Region,Quantity,Price,Total Sales
10,1011,2026-01-11,Porkodi,Laptop,Chennai,1,52000,52000
11,1012,2026-01-12,Anitha,Monitor,Madurai,1,12500,12500
12,1013,2026-01-13,Arjun,Mouse,Vellore,4,500,2000
13,1014,2026-01-14,Meena,Headphones,Salem,1,2000,2000
14,1015,2026-01-15,Ravi,Phone,Chennai,1,21000,21000

In [16]:
#data set info and check the null value
sales_data.info()

sales_data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      15 non-null     int64
 1   Date         15 non-null     object
 2   Customer     15 non-null     object
 3   Product      15 non-null     object
 4   Region       15 non-null     object
 5   Quantity     15 non-null     int64
 6   Price        15 non-null     int64
 7   Total Sales  15 non-null     int64
dtypes: int64(4), object(4)
memory usage: 1.1+ KB

OrderID        0
Date           0
Customer       0
Product        0
Region         0
Quantity       0
Price          0
Total Sales    0
dtype: int64

In [17]:
## What is total revenue?
Total_Revenue = sales_data["Total Sales"].agg("sum")
print("Total Revenue = ",Total_Revenue)

Total Revenue =  259500

In [18]:
## What is mximum sales price?
maximum_sales=sales_data["Total Sales"].max()
print("Maximum Sales  : ",maximum_sales)

Maximum Sales  :  55000

In [19]:
## How to view only selected columns?
sales_data[["Customer", "Product", "Total Sales"]]

   Customer     Product  Total Sales
0      Asha      Laptop        50000
1      Ravi       Mouse         1000
2     Kiran    Keyboard         1500
3     Meena       Phone        20000
4     Arjun      Laptop        55000
5     Divya  Headphones         4000
6     Kavin     Monitor        12000
7      Nila       Mouse         1500
8     Rahul    Keyboard         3000
9     Laksh       Phone        22000
10  Porkodi      Laptop        52000
11   Anitha     Monitor        12500
12    Arjun       Mouse         2000
13    Meena  Headphones         2000
14     Ravi       Phone        21000

In [20]:
##Sales by product with count
sales_data.groupby("Product")["Price"].agg(["sum","count"])

               sum  count
Product
Headphones    4000      2
Keyboard      3000      2
Laptop      157000      3
Monitor      24500      2
Mouse         1500      3
Phone        63000      3

In [32]:
#What is the MINIMUM sales amount?
Minimum_sales = sales_data["Total Sales"].min()
print("Minimum_sales:",Minimum_sales)

Minimum_sales: 1000

In [36]:
#What is the average sales amount?
Average_sales = sales_data.groupby("Product")["Total Sales"].mean()
print(Average_sales)

Product
Headphones     3000.000000
Keyboard       2250.000000
Laptop        52333.333333
Monitor       12250.000000
Mouse          1500.000000
Phone         21000.000000
Name: Total Sales, dtype: float64

In [39]:
#Which products were sold most frequently?
sales_data["Product"].value_counts()

Product
Laptop        3
Mouse         3
Phone         3
Keyboard      2
Headphones    2
Monitor       2
Name: count, dtype: int64

In [40]:
#Sort sales from highest to lowest
sales_data.sort_values(by="Total Sales", ascending=False)

,OrderID,Date,Customer,Product,Region,Quantity,Price,Total Sales
4,1005,2026-01-05,Arjun,Laptop,Vellore,1,55000,55000
10,1011,2026-01-11,Porkodi,Laptop,Chennai,1,52000,52000
0,1001,2026-01-01,Asha,Laptop,Chennai,1,50000,50000
9,1010,2026-01-10,Laksh,Phone,Chennai,1,22000,22000
14,1015,2026-01-15,Ravi,Phone,Chennai,1,21000,21000
3,1004,2026-01-04,Meena,Phone,Chennai,1,20000,20000
11,1012,2026-01-12,Anitha,Monitor,Madurai,1,12500,12500
6,1007,2026-01-07,Kavin,Monitor,Chennai,1,12000,12000
5,1006,2026-01-06,Divya,Headphones,Salem,2,2000,4000
8,1009,2026-01-09,Rahul,Keyboard,Erode,2,1500,3000
12,1013,2026-01-13,Arjun,Mouse,Vellore,4,500,2000
13,1014,2026-01-14,Meena,Headphones,Salem,1,2000,2000
2,1003,2026-01-03,Kiran,Keyboard,Madurai,1,1500,1500
7,1008,2026-01-08,Nila,Mouse,Trichy,3,500,1500
1,1002,2026-01-02,Ravi,Mouse,Chennai,2,500,1000

In [41]:
#Show only high sales transactions (>20000)
sales_data[sales_data["Total Sales"] > 20000]

    OrderID       Date Customer Product   Region  Quantity  Price  Total Sales
0      1001 2026-01-01     Asha  Laptop  Chennai         1  50000        50000
4      1005 2026-01-05    Arjun  Laptop  Vellore         1  55000        55000
9      1010 2026-01-10    Laksh   Phone  Chennai         1  22000        22000
10     1011 2026-01-11  Porkodi  Laptop  Chennai         1  52000        52000
14     1015 2026-01-15     Ravi   Phone  Chennai         1  21000        21000

In [44]:
#which region has highest count?
sales_data.groupby("Region")["Total Sales"].sum()

Region
Chennai    8
Erode      2
Madurai    2
Salem      3
Trichy     3
Vellore    5
Name: Quantity, dtype: int64

In [47]:
#Create summary report and export CSV
summary = sales_data.groupby("Product")["Total Sales"].sum().reset_index()
print(summary)
summary.to_csv("sales_summary.csv", index=False)

      Product  Total Sales
0  Headphones         6000
1    Keyboard         4500
2      Laptop       157000
3     Monitor        24500
4       Mouse         4500
5       Phone        63000

In [48]:
import os
os.getcwd()

'C:\\Users\\admin\\PORKODI CLG\\Data-Science-Learning\\SalesData'